version: "3"

networks:
  cluster-kafka:
    driver: bridge
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - cluster-kafka
  kafka-0:
    image: docker.io/bitnami/kafka:2.8.1
    container_name: kafka-0
    hostname: kafka-0
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS= PLAINTEXT://kafka-0:9092,CONNECTIONS_FROM_HOST://localhost:19092
      - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://kafka-0:9092,CONNECTIONS_FROM_HOST://localhost:19092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME= PLAINTEXT
      - KAFKA_INTER_BROKER_USER=kafka
    volumes:
      - kafka_0_data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - cluster-kafka
  kafka-1:
    image: docker.io/bitnami/kafka:2.8.1
    container_name: kafka-1
    hostname: kafka_1
    ports:
      - "9093:9092"
      - "19093:19092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS= PLAINTEXT://kafka-1:9092,CONNECTIONS_FROM_HOST://localhost:19093
      - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://kafka-1:9092,CONNECTIONS_FROM_HOST://localhost:19093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME= PLAINTEXT
      - KAFKA_INTER_BROKER_USER=kafka
    volumes:
      - kafka_1_data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - cluster-kafka
  kafka-2:
    image: docker.io/bitnami/kafka:2.8.1
    container_name: kafka-2
    hostname: kafka-2
    ports:
      - "9094:9092"
      - "19094:19092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=2
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS= PLAINTEXT://kafka-2:9092,CONNECTIONS_FROM_HOST://localhost:19094
      - KAFKA_ADVERTISED_LISTENERS= PLAINTEXT://kafka-2:9092,CONNECTIONS_FROM_HOST://localhost:19094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME= PLAINTEXT
      - KAFKA_INTER_BROKER_USER=kafka
    volumes:
      - kafka_2_data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - cluster-kafka
  presto:
    image: ahanaio/prestodb-sandbox
    ports:
      - '8080:8080'
    expose:
      - '8080'
    volumes:
      - ./presto_etc/catalog/kafka.properties:/opt/presto-server/etc/catalog/kafka.properties
      - ./presto_etc/kafka:/opt/presto-server/etc/kafka
volumes:
  zookeeper_data:
    driver: local
  kafka_0_data:
    driver: local
  kafka_1_data:
    driver: local
  kafka_2_data:
    driver: local